### ISSUE TITLE
Mapa Mental de Conjuntos 

### ISSUE THREAD

**Issue by Berenice1719** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Berenice1719#2]
[Mapa Mental Matematicas Discretas.pdf](https://github.com/user-attachments/files/17090888/Mapa.Mental.Matematicas.Discretas.pdf)

**Comment by UsuarioIncognito** [comment]
Exposición de Ideas Centrales: 5/5
Redacción y Ortografía: 5/5
Presentación visual: 5/5
Referencias: 5/5
Calificación Final: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
